language: node_js
node_js:
- 6.11.5
install:
- npm install
cache:
  directories:
  - /node_modules
after_success:
- npm run build
- ./node_modules/.bin/firebase deploy -P dev --token $FIREBASE_DEPLOY_TOKEN
notifications:
  email: false