language: node_js
node_js:
- lts/*
before_script:
- cd functions
- npm install -g firebase tools
- npm install
cache:
  directories:
  - functions/node_modules
after_success:
- ./node_modules/.bin/firebase deploy --only functions --token $FIREBASE_DEPLOY_TOKEN