language: node_js
node_js:
- lts/*
before_script:
- cd functions
- npm install -g firebase-tools
- npm install
cache:
  directories:
  - functions/node_modules
after_success:
- firebase deploy --only functions -P production --token $FIREBASE_DEPLOY_TOKEN