language: node_js
node_js:
- 6.11.5
before_install:
- cd functions
- bash creds.sh
install:
- npm install
cache:
  directories:
  - functions/node_modules
after_success:
- pwd
- ls
- bash deploy.sh
notifications:
  email: false