language: node_js
before_script:
- cd functions
- npm install -g firebase-tools
- npm install
cache:
  directories:
  - /node_modules
after_success:
- npm run build
- firebase deploy -P dev --token $FIREBASE_DEPLOY_TOKEN